//CREATE UNIQUE
###
POST http://localhost:9000/api/forms HTTP/1.1
content-Type: application/json

{
    "data":"",
    "client":"svv",
    "professional":"ccvdfs"
}

//ALL GET
###
GET http://localhost:9000/api/forms HTTP/1.1

//UNIQUE GET
###
GET http://localhost:9000/api/forms/639e633ba6078c4a78ad4195 HTTP/1.1

###
GET http://localhost:9000/api/forms/professional/ccvdfs HTTP/1.1

###
GET http://localhost:9000/api/forms/client/svv HTTP/1.1

//UPDATE UNIQUE ID
###
PUT  http://localhost:9000/api/forms/639e633ba6078c4a78ad4195 HTTP/1.1
content-Type: application/json

{
    "data":"05032023",
    "client":"dddd",
    "professional":"nfgidfadfcdudvdasf"
}
###
DELETE   http://localhost:9000/api/forms/639e6299c7634dfd7561b825 HTTP/1.1
