//CREATE UNIQUE
###
POST  https://appointmentibiocd.azurewebsites.net/api/files HTTP/1.1
content-Type: application/json

{
    "laboratory":"https://",
    "prescriptions":"https://",
    "stadies":"https://",
    "odontogram":"ggewrasdsad24fdfasd",
    "form":"639e633ba6078c4a78ad4195",
    "patient":"639e5b3678539b79cd8dfbe1",
    "medical":"639e34145bb5f9cceeaa8a6a"
}

//ALL GET
###
GET  https://appointmentibiocd.azurewebsites.net/api/files HTTP/1.1

//GET UNIQUE ID
###
GET  https://appointmentibiocd.azurewebsites.net/api/files/63fe3784bb9969df2bc76476 HTTP/1.1

###
GET  https://appointmentibiocd.azurewebsites.net/api/files/medical/639e34145bb5f9cceeaa8a6a HTTP/1.1

###
GET  https://appointmentibiocd.azurewebsites.net/api/files/patient/639e5b3678539b79cd8dfbe1 HTTP/1.1

//UPDATE UNIQUE ID
###
PUT   https://appointmentibiocd.azurewebsites.net/api/files/63fe3784bb9969df2bc76476 HTTP/1.1
content-Type: application/json

{
      "laboratory": "",
      "prescriptions": "",
      "stadies": "",
      "odontogram": "",
      "form": "",
      "patient": "63fc8c07c1cf7e926f9e65ed",
      "medical": "63fc8c07c1cf7e926f9e65eb",
      "createdAt": "2023-02-28T17:19:00.424Z",
      "updatedAt": "2023-03-09T18:38:25.971Z"
}
###
DELETE    https://appointmentibiocd.azurewebsites.net/api/files/640a23609d190c8b2752395f HTTP/1.1
