//CREATE UNIQUE
###
POST  https://ibiocdappointment.azurewebsites.net/api/files HTTP/1.1
content-Type: application/json

{
    "laboratory":"https://",
    "prescriptions":"https://",
    "stadies":"https://",
    "odontogram":"ggewrasdsad24fdfasd",
    "patient":"ggewr234324fdfasd",
    "medical":"nfgidfadfcdudvdasf"
}

//ALL GET
###
GET  https://ibiocdappointment.azurewebsites.net/api/files HTTP/1.1

//GET UNIQUE ID
###
GET  https://ibiocdappointment.azurewebsites.net/api/files/639e5e8949faa98335149024 HTTP/1.1

###
GET  https://ibiocdappointment.azurewebsites.net/api/files/medical/nfgidfadfcdudvdasf HTTP/1.1

###
GET  https://ibiocdappointment.azurewebsites.net/api/files/patient/ggewr234324fdfasd HTTP/1.1

//UPDATE UNIQUE ID
###
PUT   https://ibiocdappointment.azurewebsites.net/api/files/639e5e8949faa98335149024 HTTP/1.1
content-Type: application/json

{
    "laboratory":"http://",
    "prescriptions":"http://",
    "stadies":"http://",
    "odontogram":"ggewrasdsad24fdfasd",
    "patient":"ggewr234324fdfasd",
    "medical":"nfgidfadfcdudvdasf"
}
###
DELETE    https://ibiocdappointment.azurewebsites.net/api/files/639e4fea47baef21c5416c9d HTTP/1.1
