//CREATE UNIQUE
###
POST  https://appointmentibiocd.azurewebsites.net/api/specialty HTTP/1.1
content-Type: application/json

{
      "title": "Blanquemiento",
      "comment": "Ver las ofertas al sacar el turno",
      "medical": "639e34145bb5f9cceeaa8a6a",
      "offer": "0.3",
      "price": "700"
}

//ALL GET
###
GET  https://appointmentibiocd.azurewebsites.net/api/specialty HTTP/1.1

//GET UNIQUE 
###
GET  https://appointmentibiocd.azurewebsites.net/api/specialty/639e743b79231047a438af58 HTTP/1.1


//UPDATE UNIQUE ID
###
PUT   https://appointmentibiocd.azurewebsites.net/api/specialty/63e64c06fa93a3b883b5e7ac HTTP/1.1
content-Type: application/json

{
      "title": "Blanquemiento",
      "comment": "Ver las ofertas al sacar el turno",
      "medical": "639e34145bb5f9cceeaa8a6a",
      "offer": "0.3",
      "price": "700",
}

###
DELETE    https://appointmentibiocd.azurewebsites.net/api/specialty/63f57e96b2b362681dd5bab4 HTTP/1.1
