//CREATE UNIQUE
###
POST  https://appointmentibiocd.azurewebsites.net/api/favs HTTP/1.1
content-Type: application/json

{
    "medical":"63e3061d144420347e26aadd4ec",
    "patient":"639e5b3678539b79cd8dfbe1"

}

//ALL GET
###
GET  https://appointmentibiocd.azurewebsites.net/api/favs HTTP/1.1

//GET UNIQUE 
###
GET  https://appointmentibiocd.azurewebsites.net/api/favs/639e5b3678539b79cd8dfbe1 HTTP/1.1

###
GET  https://appointmentibiocd.azurewebsites.net/api/favs/medical/639e34145bb5f9cceeaa8a6a HTTP/1.1

###
GET  https://appointmentibiocd.azurewebsites.net/api/favs/patient/639e5b3678539b79cd8dfbe1 HTTP/1.1

//UPDATE UNIQUE ID
###
PUT  https://appointmentibiocd.azurewebsites.net/api/favs/63e2e1444151c716ea4b0d2c HTTP/1.1
content-Type: application/json

{
    "medical":"639e34145bb5f9cceeaa8a6a",
    "patient":"639e5b3678539b79cd8dfbe1"
}

###
DELETE    https://appointmentibiocd.azurewebsites.net/api/favs/63e2e1444151c716ea4b0d2c HTTP/1.1
