//CREATE UNIQUE
###
POST  https://ibiocdappointment.azurewebsites.net/api/offers HTTP/1.1
content-Type: application/json

{
    "medical":"639e34145bb5sadceeaa8a6a",
    "code":"5454FDFF",
    "fecha":"20032023",
    "percentage":"0.3",
    "title":"FARMACITY",
    "specialty":"adsfadvadscdasc"
}

//ALL GET
###
GET  https://ibiocdappointment.azurewebsites.net/api/offers HTTP/1.1

//GET UNIQUE 
###
GET  https://ibiocdappointment.azurewebsites.net/api/offers/639e7564c0df17739ae36210 HTTP/1.1

###
GET  https://ibiocdappointment.azurewebsites.net/api/offers/medical/639e34145bb5f9cceeaa8a6a HTTP/1.1


//UPDATE UNIQUE ID
###
PUT   https://ibiocdappointment.azurewebsites.net/api/offers/639e7564c0df17739ae36210 HTTP/1.1
content-Type: application/json

{
    "medical":"639e34145bb5f9cceeaa8a6a",
    "code":"5454FDFF",
    "fecha":"20032023",
    "percentage":"0.2",
    "title":"FARMACITY",
    "specialty":"adsfadvadscdasc"
}

###
DELETE    https://ibiocdappointment.azurewebsites.net/api/offers/639e744c79231047a438af5c HTTP/1.1
