odontogram//CREATE UNIQUE
###
POST  https://ibiocdappointment.azurewebsites.net/api/odontogram HTTP/1.1
content-Type: application/json

{
    "data":"asd",
    "patient":"svv",
    "medical":"ccvdfs"
}

//ALL GET
###
GET  https://ibiocdappointment.azurewebsites.net/api/odontogram HTTP/1.1

//UNIQUE GET
###
GET  https://ibiocdappointment.azurewebsites.net/api/odontogram/639e6b1ac26ea5675c1ae284 HTTP/1.1

###
GET  https://ibiocdappointment.azurewebsites.net/api/odontogram/medical/ccvdfs HTTP/1.1

###
GET  https://ibiocdappointment.azurewebsites.net/api/odontogram/patient/svv HTTP/1.1

//UPDATE UNIQUE ID
###
PUT   https://ibiocdappointment.azurewebsites.net/api/odontogram/639e6b1ac26ea5675c1ae284 HTTP/1.1
content-Type: application/json

{
    "data":"05032023",
    "patient":"svv",
    "medical":"ccvdfs"
}
###
DELETE    https://ibiocdappointment.azurewebsites.net/api/odontogram/639e649e4be659baa2a6006b HTTP/1.1
