###
POST  https://appointmentibiocd.azurewebsites.net/api/patient HTTP/1.1
content-Type: application/json

{
    
    "name_last":"xdxdxcb Garcia",
    "dni":"18032170",
    "phone":"1191119340",
    "email":"maximialiano.g@gmail.com",
    "direction":"dooc",
    "img":"//sadas",
    "token_not":"//sadas"
}

###
GET  https://appointmentibiocd.azurewebsites.net/api/patient HTTP/1.1


###
GET https://appointmentibiocd.azurewebsites.net/api/patient/639e5b3678539b79cd8dfbe1 HTTP/1.1

###
GET https://appointmentibiocd.azurewebsites.net/api/patient/email/maximiliano.g@gmail.com HTTP/1.1


###
PUT   https://appointmentibiocd.azurewebsites.net/api/patient/63fc8c07c1cf7e926f9e65ed HTTP/1.1
content-Type: application/json

{
    "name_last": "Adrian Herrera",
    "dni": "42121008",
    "phone": "11525434828",
    "email": "adrianherrera.r.e@gmail.com",
    "direction": "::",
    "img": "",
    "token_not":""
}
###
DELETE   https://appointmentibiocd.azurewebsites.net/api/patient/64123fb5b61dc908f81ad80a HTTP/1.1
